### ISSUE TITLE
Move frequently-changed properties up in the generated POM

### ISSUE THREAD

**Issue by braveulysses** [pingidentity/server-sdk-maven#29]
Arno suggested updating the POM generated by the archetype so that those properties that need to be updated most frequently are at the top. This makes them easier to find, which is a small but significant QOL improvement for anybody who writes a lot of extensions.

> this is  what my properties look like:
> ```
>   <properties>
>     <extension.vendor.contact>arno@pingidentity.com</extension.vendor.contact>
>     <server-sdk.version>8.1.0.0</server-sdk.version>
>     <include.source>true</include.source>
>     <source.version>1.8</source.version>
>     <target.version>1.8</target.version>
>     <server-sdk.maven-version>${server-sdk.version}</server-sdk.maven-version>
>     <extension.name>${project.name}</extension.name>
>     <extension.version>${project.version}</extension.version>
>     <extension.vendor.name>${project.organization.name}</extension.vendor.name>
>     <extension.vendor.id>${project.groupId}</extension.vendor.id>
>     <extension.vendor.url>${project.organization.url}</extension.vendor.url>
>     <maven.build.timestamp.format>yyyyMMddHHmmss'Z'</maven.build.timestamp.format>
>     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>   </properties>
> ```
> the first one **always** needs to be updated
> the second **may change**, albeit infrequently
> the third could be flipped to false in rare occasions

**Comment by arnaudlacour** [comment]
can I just say: thank you!
It may seem like 'small improvements' but they  go  a long way!

**Comment by kenneth-ping** [comment]
Woot!

**Comment by braveulysses** [comment]
OK, these changes are in, and I'm currently publishing the new release (1.0.16) to Maven Central.
